// PM2 Ecosystem Configuration
// Auto-generated by Wingman - do not edit manually
module.exports = {
  "apps": [
    {
      "name": "honest-ivory-thicket-app-wingman-coworker",
      "namespace": "wingman-apps",
      "script": "bash",
      "args": [
        "-c",
        "set -a; [ -f .env ] && . ./.env; set +a; export APP_ID='98f98e25-2899-4992-b576-8ae9f4e54026' APP_LABEL='Wingman Coworker' USER_ALIAS='honest-ivory-thicket' PORT=41003; sh -c 'bunx vite preview --host 0.0.0.0 --port ${PORT:-8093} --strictPort'"
      ],
      "cwd": "/Users/mini/code/superbased/coworker/coworker-fe",
      "out_file": "/Users/mini/code/superbased/coworker/coworker-fe/apps/logs/honest-ivory-thicket-app-wingman-coworker-out.log",
      "error_file": "/Users/mini/code/superbased/coworker/coworker-fe/apps/logs/honest-ivory-thicket-app-wingman-coworker-error.log",
      "log_date_format": "YYYY-MM-DD HH:mm:ss",
      "merge_logs": true,
      "autorestart": false,
      "max_restarts": 0,
      "min_uptime": "5s"
    },
    {
      "name": "honest-ivory-thicket-app-wingman-web",
      "namespace": "wingman-apps",
      "script": "bash",
      "args": [
        "-c",
        "set -a; [ -f .env ] && . ./.env; set +a; export APP_ID='5fd6fb46-eebf-4ece-ae75-8ee3c366d836' APP_LABEL='Wingman Web' USER_ALIAS='honest-ivory-thicket' PORT=41003; sh -c 'bunx vite preview --host 0.0.0.0 --port ${PORT:-8093} --strictPort'"
      ],
      "cwd": "/Users/mini/code/superbased/coworker/coworker-fe",
      "out_file": "/Users/mini/code/superbased/coworker/coworker-fe/apps/logs/honest-ivory-thicket-app-wingman-web-out.log",
      "error_file": "/Users/mini/code/superbased/coworker/coworker-fe/apps/logs/honest-ivory-thicket-app-wingman-web-error.log",
      "log_date_format": "YYYY-MM-DD HH:mm:ss",
      "merge_logs": true,
      "autorestart": false,
      "max_restarts": 0,
      "min_uptime": "5s"
    },
    {
      "name": "honest-ivory-thicket-app-wingman-flight-deck-bef",
      "namespace": "wingman-apps",
      "script": "bash",
      "args": [
        "-c",
        "set -a; [ -f .env ] && . ./.env; set +a; export APP_ID='24a79d6b-43ed-4662-a47e-e301e519f162' APP_LABEL='wingman-flight-deck-befree' USER_ALIAS='honest-ivory-thicket' PORT=41008; sh -c 'bunx vite preview --host 0.0.0.0 --port ${PORT:-8093} --strictPort'"
      ],
      "cwd": "/Users/mini/code/wingmanbefree/wingman-fd",
      "out_file": "/Users/mini/code/wingmanbefree/wingman-fd/apps/logs/honest-ivory-thicket-app-wingman-flight-deck-bef-out.log",
      "error_file": "/Users/mini/code/wingmanbefree/wingman-fd/apps/logs/honest-ivory-thicket-app-wingman-flight-deck-bef-error.log",
      "log_date_format": "YYYY-MM-DD HH:mm:ss",
      "merge_logs": true,
      "autorestart": false,
      "max_restarts": 0,
      "min_uptime": "5s"
    }
  ]
};
