/**
 * Workspace session key management.
 *
 * A workspace session key is an ephemeral Nostr keypair generated by the client,
 * encrypted to the user's own real npub via NIP-44, and stored as an opaque blob.
 * At runtime the user decrypts this blob once with their real signer, and all
 * subsequent crypto (owner-payload, record signing, NIP-98 API auth) uses the
 * workspace session key from memory.
 *
 * Trust model: user generates key → encrypts to self → server stores ciphertext
 * only → user decrypts at runtime → trust extends to the key.
 */

import {
  personalEncryptForNpub,
  personalDecryptFromNpub,
  decodeNsec,
  bytesToHex,
  secretToPubkey,
} from '../auth/nostr.js';
import { createGroupIdentity } from './group-keys.js';
import { getSharedDb } from '../db.js';
import { flightDeckLog } from '../logging.js';

// ---------------------------------------------------------------------------
// In-memory state — the active workspace session key
// ---------------------------------------------------------------------------

let _activeWsKey = null;
let _wsKeyRegistered = false;

/**
 * Set the active workspace session key after decryption.
 * @param {{ nsec: string, secret: Uint8Array, secretHex: string, npub: string, epoch: number, workspaceOwnerNpub: string }} key
 * @param {{ registered?: boolean }} options
 */
export function setActiveWorkspaceKey(key, options = {}) {
  _activeWsKey = key || null;
  _wsKeyRegistered = Boolean(options.registered);
}

/**
 * Mark the active workspace key as registered with Tower.
 * Only after this should the key be used for NIP-98 API auth.
 */
export function markWorkspaceKeyRegistered() {
  _wsKeyRegistered = true;
}

export function isWorkspaceKeyRegistered() {
  return _wsKeyRegistered;
}

export function getActiveWorkspaceKey() {
  return _activeWsKey;
}

/**
 * Returns the workspace key secret for NIP-98 auth,
 * but ONLY if Tower registration has been confirmed.
 * This prevents using the key for API auth before Tower knows about it.
 */
export function getActiveWorkspaceKeySecretForAuth() {
  if (!_wsKeyRegistered) return null;
  return _activeWsKey?.secret ?? null;
}

/**
 * Returns the workspace key secret for local crypto (owner-payload encrypt/decrypt).
 * Available regardless of registration status — local crypto doesn't need Tower.
 */
export function getActiveWorkspaceKeySecret() {
  return _activeWsKey?.secret ?? null;
}

export function getActiveWorkspaceKeyNpub() {
  return _activeWsKey?.npub ?? null;
}

export function clearActiveWorkspaceKey() {
  _activeWsKey = null;
}

/**
 * Export the active workspace key for transfer to the Web Worker.
 * Returns a plain serializable object or null.
 */
export function exportWorkspaceKeyForWorker() {
  if (!_activeWsKey) return null;
  return {
    nsec: _activeWsKey.nsec,
    npub: _activeWsKey.npub,
    epoch: _activeWsKey.epoch,
    workspaceOwnerNpub: _activeWsKey.workspaceOwnerNpub,
    registered: _wsKeyRegistered,
  };
}

/**
 * Import a workspace key from the main thread (used in the worker).
 * Accepts the serializable object from exportWorkspaceKeyForWorker().
 */
export function importWorkspaceKeyFromMain(data) {
  if (!data?.nsec || !data?.npub) {
    _activeWsKey = null;
    _wsKeyRegistered = false;
    return;
  }
  const secret = decodeNsec(data.nsec);
  _activeWsKey = {
    nsec: data.nsec,
    secret,
    secretHex: bytesToHex(secret),
    npub: data.npub,
    epoch: data.epoch ?? 1,
    workspaceOwnerNpub: data.workspaceOwnerNpub || '',
  };
  _wsKeyRegistered = Boolean(data.registered);
}

// ---------------------------------------------------------------------------
// Key generation
// ---------------------------------------------------------------------------

/**
 * Generate a new workspace session keypair.
 * Returns { nsec, npub, secret, secretHex }.
 */
export function generateWorkspaceSessionKey() {
  const identity = createGroupIdentity();
  const secret = decodeNsec(identity.nsec);
  return {
    nsec: identity.nsec,
    npub: identity.npub,
    secret,
    secretHex: bytesToHex(secret),
  };
}

// ---------------------------------------------------------------------------
// Encrypted blob — create, store, retrieve, decrypt
// ---------------------------------------------------------------------------

/**
 * Create the encrypted blob envelope for a workspace session key.
 * Encrypts the nsec to the user's own real npub via NIP-44.
 */
export async function createEncryptedKeyBlob({
  wsKeyNsec,
  wsKeyNpub,
  wsKeyEpoch = 1,
  workspaceOwnerNpub,
  userNpub,
}) {
  const encryptedNsec = await personalEncryptForNpub(userNpub, wsKeyNsec);
  return {
    version: 1,
    workspace_owner_npub: workspaceOwnerNpub,
    ws_key_npub: wsKeyNpub,
    ws_key_epoch: wsKeyEpoch,
    encrypted_nsec: encryptedNsec,
    encrypted_by_npub: userNpub,
    created_at: new Date().toISOString(),
  };
}

/**
 * Decrypt a workspace session key from its encrypted blob.
 * Returns { nsec, npub, secret, secretHex, epoch, workspaceOwnerNpub }.
 */
export async function decryptKeyBlob(blob) {
  if (!blob?.encrypted_nsec || !blob?.encrypted_by_npub) {
    throw new Error('Invalid workspace key blob: missing encrypted_nsec or encrypted_by_npub');
  }
  const nsec = await personalDecryptFromNpub(blob.encrypted_by_npub, blob.encrypted_nsec);
  const secret = decodeNsec(nsec);
  return {
    nsec,
    npub: blob.ws_key_npub,
    secret,
    secretHex: bytesToHex(secret),
    epoch: blob.ws_key_epoch ?? 1,
    workspaceOwnerNpub: blob.workspace_owner_npub || '',
  };
}

// ---------------------------------------------------------------------------
// IndexedDB cache — workspace_keys table in shared DB
// ---------------------------------------------------------------------------

function wsKeysTable() {
  return getSharedDb().workspace_keys;
}

/**
 * Cache an encrypted workspace key blob in IndexedDB.
 * @param {object} blob - The encrypted key envelope
 * @param {{ registered?: boolean }} options - Whether Tower registration has been confirmed
 */
export async function cacheWorkspaceKeyBlob(blob, options = {}) {
  if (!blob?.workspace_owner_npub) return;
  await wsKeysTable().put({
    workspace_owner_npub: blob.workspace_owner_npub,
    user_npub: blob.encrypted_by_npub || '',
    ws_key_npub: blob.ws_key_npub || '',
    ws_key_epoch: blob.ws_key_epoch ?? 1,
    encrypted_blob: blob,
    registered: Boolean(options.registered),
    cached_at: Date.now(),
  });
}

/**
 * Retrieve a cached workspace key row from IndexedDB.
 * Returns { blob, registered } or null.
 */
export async function getCachedWorkspaceKeyRow(workspaceOwnerNpub) {
  if (!workspaceOwnerNpub) return null;
  const row = await wsKeysTable().get(workspaceOwnerNpub);
  if (!row?.encrypted_blob) return null;
  return { blob: row.encrypted_blob, registered: Boolean(row.registered) };
}

/**
 * Mark a cached workspace key as registered with Tower.
 */
export async function markCachedWorkspaceKeyRegistered(workspaceOwnerNpub) {
  if (!workspaceOwnerNpub) return;
  const row = await wsKeysTable().get(workspaceOwnerNpub);
  if (row) {
    await wsKeysTable().update(workspaceOwnerNpub, { registered: true });
  }
}

/**
 * Remove a cached workspace key blob.
 */
export async function removeCachedWorkspaceKeyBlob(workspaceOwnerNpub) {
  if (!workspaceOwnerNpub) return;
  await wsKeysTable().delete(workspaceOwnerNpub);
}

// ---------------------------------------------------------------------------
// Full bootstrap flow
// ---------------------------------------------------------------------------

/**
 * Bootstrap the workspace session key for a workspace.
 *
 * 1. Check IndexedDB for a cached encrypted blob.
 * 2. If found, decrypt with the real signer (one NIP-44 operation).
 * 3. If not found, generate a new key, encrypt, cache, and (optionally) register with Tower.
 *
 * Returns the decrypted key object ready for setActiveWorkspaceKey().
 * The `onRegister` callback is called with the blob when a new key is generated,
 * so the caller can register it with Tower and store on Superbased.
 */
export async function bootstrapWorkspaceSessionKey({
  workspaceOwnerNpub,
  userNpub,
  onRegister,
}) {
  // 1. Try cached blob
  const cachedRow = await getCachedWorkspaceKeyRow(workspaceOwnerNpub);
  if (cachedRow) {
    try {
      const key = await decryptKeyBlob(cachedRow.blob);
      setActiveWorkspaceKey(key, { registered: cachedRow.registered });
      flightDeckLog('info', 'workspace-key', 'decrypted workspace session key from cache', {
        workspaceOwnerNpub,
        wsKeyNpub: key.npub,
        epoch: key.epoch,
        registered: cachedRow.registered,
      });

      // If cached but not yet registered with Tower, retry registration
      if (!cachedRow.registered && typeof onRegister === 'function') {
        try {
          await onRegister(cachedRow.blob, key);
        } catch (error) {
          flightDeckLog('warn', 'workspace-key', 'retry registration failed', {
            workspaceOwnerNpub,
            error: error?.message || String(error),
          });
        }
      }

      return key;
    } catch (error) {
      flightDeckLog('warn', 'workspace-key', 'cached blob decrypt failed, will regenerate', {
        workspaceOwnerNpub,
        error: error?.message || String(error),
      });
      await removeCachedWorkspaceKeyBlob(workspaceOwnerNpub);
    }
  }

  // 2. No cache (or cache was corrupt) — generate new key
  const generated = generateWorkspaceSessionKey();
  const blob = await createEncryptedKeyBlob({
    wsKeyNsec: generated.nsec,
    wsKeyNpub: generated.npub,
    wsKeyEpoch: 1,
    workspaceOwnerNpub,
    userNpub,
  });

  // 3. Cache locally
  await cacheWorkspaceKeyBlob(blob);

  const key = {
    nsec: generated.nsec,
    npub: generated.npub,
    secret: generated.secret,
    secretHex: generated.secretHex,
    epoch: 1,
    workspaceOwnerNpub,
  };
  setActiveWorkspaceKey(key);

  flightDeckLog('info', 'workspace-key', 'generated new workspace session key', {
    workspaceOwnerNpub,
    wsKeyNpub: generated.npub,
  });

  // 4. Notify caller to register with Tower / store on Superbased
  if (typeof onRegister === 'function') {
    try {
      await onRegister(blob, key);
    } catch (error) {
      flightDeckLog('warn', 'workspace-key', 'key registration callback failed', {
        workspaceOwnerNpub,
        error: error?.message || String(error),
      });
    }
  }

  return key;
}
